# Generated by Django 4.2.5 on 2023-09-06 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"verbose_name_plural": "crew"},
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "distance")},
        ),
    ]
