# Generated by Django 4.2.5 on 2023-09-06 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0003_alter_route_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together=set(),
        ),
    ]
