# Generated by Django 4.2.5 on 2023-09-07 10:59

from django.db import migrations, models
import train_station.models


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0004_alter_route_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_station.models.train_image_path
            ),
        ),
    ]
