# Generated by Django 4.2.5 on 2023-09-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0006_alter_route_destination_alter_route_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destination_routes",
                to="train_station.station",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_routes",
                to="train_station.station",
            ),
        ),
    ]
